### PR TITLE
Product update for Nov 10th 2023

### PR DESCRIPTION
**Pull request by sujaya-sys**

### CODE REVIEW

**Review by chrishumanitec — APPROVED** [review]
LGTM as long as its merged after the docs are published.

**Comment by sujaya-sys** [comment]
@chrishumanitec which docs are you referring to?

**Comment by chrishumanitec** [comment]
> @chrishumanitec which docs are you referring to?

These ones: https://developer.humanitec.com/platform-orchestrator/security/service-users/

So I guess good to merge.

**Comment by sujaya-sys** [comment]
@chrishumanitec I should probably link to the docs in the update 👍

**Pull request merged**
